<?php
/**
 * Created by PhpStorm.
 * User: xuchangqing
 * Date: 2017/11/3
 * Time: 上午10:43
 */
namespace  backend\base;

use yii\web\Controller as YiiController;

class Controller extends YiiController
{
    public function beforeAction($action)
    {
        if(\Yii::$app->user->isGuest)
        {
            header('Location:/site/login');
            exit;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}